-- MySQL Script generated by MySQL Workbench
-- 11/23/21 12:19:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema demo_security
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `demo_security` ;

-- -----------------------------------------------------
-- Schema demo_security
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demo_security` DEFAULT CHARACTER SET utf8mb4 ;
USE `demo_security` ;

-- -----------------------------------------------------
-- Table `demo_security`.`especialidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo_security`.`especialidades` ;

CREATE TABLE IF NOT EXISTS `demo_security`.`especialidades` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NULL DEFAULT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_TITULO` (`titulo` ASC),
  INDEX `IDX_ESPECIALIDADE_TITULO` (`titulo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `demo_security`.`horas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo_security`.`horas` ;

CREATE TABLE IF NOT EXISTS `demo_security`.`horas` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `hora_minuto` TIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_HORA_MINUTO` (`hora_minuto` ASC),
  INDEX `IDX_HORA_MINUTO` (`hora_minuto` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `demo_security`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo_security`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `demo_security`.`usuarios` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ativo` TINYINT(1) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `codigo_verificador` VARCHAR(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_USUARIO_EMAIL` (`email` ASC),
  INDEX `IDX_USUARIO_EMAIL` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `demo_security`.`medicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo_security`.`medicos` ;

CREATE TABLE IF NOT EXISTS `demo_security`.`medicos` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `crm` INT(11) NOT NULL,
  `data_inscricao` DATE NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `id_usuario` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_CRM` (`crm` ASC),
  UNIQUE INDEX `UK_NOME` (`nome` ASC),
  UNIQUE INDEX `UK_USUARIO_ID` (`id_usuario` ASC),
  CONSTRAINT `FK_USUARIO_ID`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `demo_security`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `demo_security`.`pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo_security`.`pacientes` ;

CREATE TABLE IF NOT EXISTS `demo_security`.`pacientes` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `data_nascimento` DATE NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `id_usuario` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_PACIENTE_NOME` (`nome` ASC),
  INDEX `FK_PACIENTE_USUARIO_ID` (`id_usuario` ASC),
  CONSTRAINT `FK_PACIENTE_USUARIO_ID`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `demo_security`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `demo_security`.`agendamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo_security`.`agendamentos` ;

CREATE TABLE IF NOT EXISTS `demo_security`.`agendamentos` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `data_consulta` DATE NULL DEFAULT NULL,
  `id_especialidade` BIGINT(20) NULL DEFAULT NULL,
  `id_horario` BIGINT(20) NULL DEFAULT NULL,
  `id_medico` BIGINT(20) NULL DEFAULT NULL,
  `id_paciente` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ESPECIALIDADE_ID` (`id_especialidade` ASC),
  INDEX `FK_HORA_ID` (`id_horario` ASC),
  INDEX `FK_MEDICO_ID` (`id_medico` ASC),
  INDEX `FK_PACIENTE_ID` (`id_paciente` ASC),
  CONSTRAINT `FK_ESPECIALIDADE_ID`
    FOREIGN KEY (`id_especialidade`)
    REFERENCES `demo_security`.`especialidades` (`id`),
  CONSTRAINT `FK_HORA_ID`
    FOREIGN KEY (`id_horario`)
    REFERENCES `demo_security`.`horas` (`id`),
  CONSTRAINT `FK_MEDICO_ID`
    FOREIGN KEY (`id_medico`)
    REFERENCES `demo_security`.`medicos` (`id`),
  CONSTRAINT `FK_PACIENTE_ID`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `demo_security`.`pacientes` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `demo_security`.`medicos_tem_especialidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo_security`.`medicos_tem_especialidades` ;

CREATE TABLE IF NOT EXISTS `demo_security`.`medicos_tem_especialidades` (
  `id_especialidade` BIGINT(20) NOT NULL,
  `id_medico` BIGINT(20) NOT NULL,
  UNIQUE INDEX `MEDICO_UNIQUE_ESPECIALIZACAO` (`id_especialidade` ASC, `id_medico` ASC),
  INDEX `FK_ESPECIALIDADE_MEDICO_ID` (`id_medico` ASC),
  CONSTRAINT `FK_ESPECIALIDADE_MEDICO_ID`
    FOREIGN KEY (`id_medico`)
    REFERENCES `demo_security`.`medicos` (`id`),
  CONSTRAINT `FK_MEDICO_ESPECIALIDADE_ID`
    FOREIGN KEY (`id_especialidade`)
    REFERENCES `demo_security`.`especialidades` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `demo_security`.`perfis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo_security`.`perfis` ;

CREATE TABLE IF NOT EXISTS `demo_security`.`perfis` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_PERFIL_DESCRICAO` (`descricao` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `demo_security`.`usuarios_tem_perfis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `demo_security`.`usuarios_tem_perfis` ;

CREATE TABLE IF NOT EXISTS `demo_security`.`usuarios_tem_perfis` (
  `usuario_id` BIGINT(20) NOT NULL,
  `perfil_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`usuario_id`, `perfil_id`),
  INDEX `FK_USUARIO_TEM_PERFIL_ID` (`perfil_id` ASC),
  INDEX `FK_PERFIL_TEM_USUARIO_ID` (`usuario_id` ASC),
  CONSTRAINT `FK_PERFIL_TEM_USUARIO_ID`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `demo_security`.`usuarios` (`id`),
  CONSTRAINT `FK_USUARIO_TEM_PERFIL_ID`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `demo_security`.`perfis` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
